/* =============================================================
   Generated by website_sdk — safe to re-run from the agent.
   Hooks nav toggle, smooth scroll, form submission, and a simple
   lightbox for any .photo-gallery pages.
   ============================================================= */

document.addEventListener('DOMContentLoaded', function () {

    const navToggle = document.querySelector('.nav-toggle');
    const navLinks = document.querySelector('.nav-links');
    if (navToggle && navLinks) {
        navToggle.addEventListener('click', function () {
            navToggle.classList.toggle('active');
            navLinks.classList.toggle('open');
        });
        navLinks.querySelectorAll('a').forEach(function (link) {
            link.addEventListener('click', function () {
                navToggle.classList.remove('active');
                navLinks.classList.remove('open');
            });
        });
    }

    const currentPage = window.location.pathname.split('/').pop() || 'index.html';
    document.querySelectorAll('.nav-links a').forEach(function (link) {
        const href = link.getAttribute('href');
        if (!href) return;
        if (href === currentPage || (currentPage === '' && href === 'index.html')) {
            link.classList.add('active');
        }
    });

    const contactForm = document.getElementById('contact-form');
    const formMessage = document.getElementById('form-message');
    if (contactForm) {
        contactForm.addEventListener('submit', function (e) {
            e.preventDefault();
            const submitBtn = contactForm.querySelector('button[type="submit"]');
            const originalText = submitBtn.textContent;
            submitBtn.textContent = 'Sending...';
            submitBtn.disabled = true;
            const formData = new FormData(contactForm);
            fetch('https://api.web3forms.com/submit', { method: 'POST', body: formData })
                .then(function (r) { return r.json(); })
                .then(function (d) {
                    if (d.success) {
                        formMessage.className = 'form-message success';
                        formMessage.textContent = 'Thanks! We received your message and will reply shortly.';
                        contactForm.reset();
                    } else {
                        formMessage.className = 'form-message error';
                        formMessage.textContent = 'Something went wrong. Please email us directly.';
                    }
                })
                .catch(function () {
                    formMessage.className = 'form-message error';
                    formMessage.textContent = 'Something went wrong. Please email us directly.';
                })
                .finally(function () {
                    submitBtn.textContent = originalText;
                    submitBtn.disabled = false;
                });
        });
    }

    const galleryItems = document.querySelectorAll('.gallery-item img');
    const lightbox = document.getElementById('lightbox');
    const lightboxImg = document.getElementById('lightbox-img');
    if (galleryItems.length > 0 && lightbox && lightboxImg) {
        galleryItems.forEach(function (img) {
            img.addEventListener('click', function () {
                lightboxImg.src = img.src;
                lightboxImg.alt = img.alt;
                lightbox.classList.add('active');
                document.body.style.overflow = 'hidden';
            });
        });
        lightbox.addEventListener('click', function (e) {
            if (e.target !== lightboxImg) {
                lightbox.classList.remove('active');
                document.body.style.overflow = '';
            }
        });
        document.addEventListener('keydown', function (e) {
            if (e.key === 'Escape' && lightbox.classList.contains('active')) {
                lightbox.classList.remove('active');
                document.body.style.overflow = '';
            }
        });
    }

    document.querySelectorAll('a[href^="#"]').forEach(function (anchor) {
        anchor.addEventListener('click', function (e) {
            const target = document.querySelector(this.getAttribute('href'));
            if (target) {
                e.preventDefault();
                target.scrollIntoView({ behavior: 'smooth', block: 'start' });
            }
        });
    });

    // --- Blog post search --- (used on blog/index.html where the search box exists)
    const searchInput = document.getElementById('post-search-input');
    const grid = document.getElementById('post-grid');
    const counter = document.getElementById('post-search-count');
    const empty = document.getElementById('post-search-empty');
    if (searchInput && grid) {
        const cards = Array.from(grid.querySelectorAll('.post-card'));
        const total = cards.length;
        const apply = function () {
            const q = (searchInput.value || '').trim().toLowerCase();
            let shown = 0;
            cards.forEach(function (card) {
                const blob = (card.dataset.search || '').toLowerCase();
                const tokens = q.split(/\s+/).filter(Boolean);
                const match = tokens.length === 0
                    ? true
                    : tokens.every(function (t) { return blob.indexOf(t) !== -1; });
                card.style.display = match ? '' : 'none';
                if (match) shown += 1;
            });
            if (counter) counter.textContent = String(shown);
            if (empty) empty.hidden = shown !== 0;
        };
        searchInput.addEventListener('input', apply);
        // Persist the query across reloads via the URL hash.
        if (window.location.hash.startsWith('#q=')) {
            try {
                searchInput.value = decodeURIComponent(window.location.hash.slice(3));
                apply();
            } catch (_) { /* ignore */ }
        }
        searchInput.addEventListener('change', function () {
            const q = (searchInput.value || '').trim();
            if (q) {
                history.replaceState(null, '', '#q=' + encodeURIComponent(q));
            } else if (window.location.hash) {
                history.replaceState(null, '', window.location.pathname);
            }
        });
    }
});
